### ISSUE TITLE
Add Libretube

### ISSUE THREAD

**Issue by davidcollini** [IronMaltese/YouTube-Frontend-Comparison#2]
I’m planning on adding Libretube, but I don’t have any way of testing it since I don’t have an android phone, All help is appreciated!

**Comment by davidcollini** [comment]
@Bnyro Can you check that the features listed for Libretube are accurate on the Read.me

**Comment by Bnyro** [comment]
Just some minor things :)
Return YouTube Dislike is supported too as in Piped, LBRY can be selected as stream source too if that is what LBRY support means :)

**Comment by davidcollini** [comment]
@Bnyro Thanks for the help!

**Comment by davidcollini** [comment]
> Just some minor things :)
> Return YouTube Dislike is supported too as in Piped, LBRY can be selected as stream source too if that is what LBRY support means :)

I specified exactly what Lbry support actually means for each application, so it should be more accurate now

**Comment by Bnyro** [comment]
With today's update, we support subscriptions without account too :)
